name: Test

on:
  push: {}

jobs:
  job_a:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  job_b:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  notify:
    runs-on: ubuntu-latest
    needs:
      - job_a
      - job_b
    steps:
      - if: ${{ Object.entries(needs).filter(e => e[1]['result'] != 'success').length > 0}}
        run: echo failed

#           allJobsSucceeded=$(echo '${{ toJson(needs) }}' | jq '. | with_entries( select(.value.result != "success") ) | length == 0')
#           if [ $allJobsSucceeded != "0" ];
#           then
#             echo "::set-output name=status::failure"
#           else
#             echo "::set-output name=status::success"
#           fi
