name: Test

on:
  push: {}

jobs:
  job_a:
    steps:
      - run: exit 0
  job_b:
    steps:
      - run: exit 0
  notify:
    needs:
      - job_a
      - job_b
    steps:
      - run: echo ${{ toJson(needs) }}
